name: Dependabot Reviewer

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  review-dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot review call
        id: dependabot-review
        uses: JaCraig/Centralized-Workflows/.github/workflows/dependabot-reviewer.yml@main
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}