name: Document Site Publish

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  publish-docs:
    uses: JaCraig/Centralized-Workflows/.github/workflows/docsfx.yml@main
    with:
      dotnet-version: '8.0.x'